name: publish-prerelease
on:
  workflow_dispatch:
    inputs:
      pre-release-tag:
        description: 'The pre-release tag use in the version'
        required: false
        default: 'pre'
      dist-tag:
        description: 'The dist-tag use'
        required: false
        default: 'next'
      dependencies-to-update:
        description: 'csv of dependencies to update with the dist-tag'
        required: false
        default: '@adobe/aio-lib-core-errors,@adobe/aio-lib-core-logging,@adobe/aio-lib-core-tvm,adobe/aio-lib-env'

jobs:
  checkout:
    uses: adobe/aio-reusable-workflows/.github/workflows/prerelease.yml@main
    secrets: inherit